name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - name: Check out code from repo
      uses: actions/checkout@v2
      
    - name: rust-cargo
      uses: actions-rs/cargo@v1.0.1
      with:
        command: build
    # Toolchain to use (without the `+` sign, ex. `nightly`)
#         toolchain: # optional
    # Arguments for the cargo command
#         args: # optional
    # Use cross instead of cargo
#         use-cross: # optional
